In [1]:
import numpy as np
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
import seaborn as sns
import yfinance as yf

from sklearn.model_selection import GridSearchCV, RandomizedSearchCV 

pd.options.mode.chained_assignment = None
pd.set_option('display.max_columns', 100)

In [2]:
stocks = ['AAPL.O', 'MSFT.O', 'INTC.O', 'AMZN.O', 'GS.N']

## Results of Grid Search for optimal number of lag returns to use

In [3]:
test = pd.read_csv('lag_grid_search.csv', 
                 index_col = 0)

display = 3

test.head(display)

,AAPL.O mean ret,MSFT.O mean ret,INTC.O mean ret,AMZN.O mean ret,GS.N mean ret,AAPL.O ret,MSFT.O ret,INTC.O ret,AMZN.O ret,GS.N ret,AAPL.O improvs,MSFT.O improvs,INTC.O improvs,AMZN.O improvs,GS.N improvs,AAPL.O falses,MSFT.O falses,INTC.O falses,AMZN.O falses,GS.N falses,AAPL.O falses.1,MSFT.O falses.1,INTC.O falses.1,AMZN.O falses.1,GS.N falses.1,AAPL.O f1 mean,MSFT.O f1 mean,INTC.O f1 mean,AMZN.O f1 mean,GS.N f1 mean,AAPL.O f1 std,MSFT.O f1 std,INTC.O f1 std,AMZN.O f1 std,GS.N f1 std
0,0.077936,-0.155093,0.042136,-0.104213,0.171643,0.561194,0.382017,0.352298,0.46192,0.443409,565.0,320.0,553.0,423.0,650.0,182.755245,188.840160,185.297702,182.582418,185.976024,10.144606,10.071168,9.439136,9.509230,9.613710,0.586011,0.597371,0.635753,0.668893,0.615714,0.029480,0.029270,0.026630,0.024903,0.028137
1,-0.025534,-0.186592,0.002942,-0.139983,0.064148,0.489204,0.366935,0.325092,0.43199,0.406156,465.0,309.0,487.0,367.0,559.0,185.530470,190.954046,186.332667,183.441558,188.131868,9.530861,9.695044,9.332536,8.979801,9.438252,0.588935,0.600621,0.642928,0.671501,0.618356,0.027302,0.028893,0.026742,0.024196,0.027880
2,-0.053306,-0.179221,-0.027866,-0.126996,0.038964,0.473628,0.373694,0.307866,0.41874,0.386402,456.0,286.0,466.0,376.0,543.0,186.378621,191.836164,187.302697,183.040959,189.066933,9.444549,9.636759,10.041677,9.510485,9.351177,0.594889,0.605392,0.646678,0.675541,0.622136,0.028107,0.028659,0.027761,0.024343,0.027275

In [4]:
test.sort_values(by="AAPL.O mean ret", ascending=False).head(display)

,AAPL.O mean ret,MSFT.O mean ret,INTC.O mean ret,AMZN.O mean ret,GS.N mean ret,AAPL.O ret,MSFT.O ret,INTC.O ret,AMZN.O ret,GS.N ret,AAPL.O improvs,MSFT.O improvs,INTC.O improvs,AMZN.O improvs,GS.N improvs,AAPL.O falses,MSFT.O falses,INTC.O falses,AMZN.O falses,GS.N falses,AAPL.O falses.1,MSFT.O falses.1,INTC.O falses.1,AMZN.O falses.1,GS.N falses.1,AAPL.O f1 mean,MSFT.O f1 mean,INTC.O f1 mean,AMZN.O f1 mean,GS.N f1 mean,AAPL.O f1 std,MSFT.O f1 std,INTC.O f1 std,AMZN.O f1 std,GS.N f1 std
0,0.077936,-0.155093,0.042136,-0.104213,0.171643,0.561194,0.382017,0.352298,0.46192,0.443409,565.0,320.0,553.0,423.0,650.0,182.755245,188.840160,185.297702,182.582418,185.976024,10.144606,10.071168,9.439136,9.509230,9.613710,0.586011,0.597371,0.635753,0.668893,0.615714,0.029480,0.029270,0.026630,0.024903,0.028137
1,-0.025534,-0.186592,0.002942,-0.139983,0.064148,0.489204,0.366935,0.325092,0.43199,0.406156,465.0,309.0,487.0,367.0,559.0,185.530470,190.954046,186.332667,183.441558,188.131868,9.530861,9.695044,9.332536,8.979801,9.438252,0.588935,0.600621,0.642928,0.671501,0.618356,0.027302,0.028893,0.026742,0.024196,0.027880
2,-0.053306,-0.179221,-0.027866,-0.126996,0.038964,0.473628,0.373694,0.307866,0.41874,0.386402,456.0,286.0,466.0,376.0,543.0,186.378621,191.836164,187.302697,183.040959,189.066933,9.444549,9.636759,10.041677,9.510485,9.351177,0.594889,0.605392,0.646678,0.675541,0.622136,0.028107,0.028659,0.027761,0.024343,0.027275

In [5]:
test.sort_values(by="AAPL.O improvs", ascending=False).head(display)

,AAPL.O mean ret,MSFT.O mean ret,INTC.O mean ret,AMZN.O mean ret,GS.N mean ret,AAPL.O ret,MSFT.O ret,INTC.O ret,AMZN.O ret,GS.N ret,AAPL.O improvs,MSFT.O improvs,INTC.O improvs,AMZN.O improvs,GS.N improvs,AAPL.O falses,MSFT.O falses,INTC.O falses,AMZN.O falses,GS.N falses,AAPL.O falses.1,MSFT.O falses.1,INTC.O falses.1,AMZN.O falses.1,GS.N falses.1,AAPL.O f1 mean,MSFT.O f1 mean,INTC.O f1 mean,AMZN.O f1 mean,GS.N f1 mean,AAPL.O f1 std,MSFT.O f1 std,INTC.O f1 std,AMZN.O f1 std,GS.N f1 std
0,0.077936,-0.155093,0.042136,-0.104213,0.171643,0.561194,0.382017,0.352298,0.46192,0.443409,565.0,320.0,553.0,423.0,650.0,182.755245,188.840160,185.297702,182.582418,185.976024,10.144606,10.071168,9.439136,9.509230,9.613710,0.586011,0.597371,0.635753,0.668893,0.615714,0.029480,0.029270,0.026630,0.024903,0.028137
1,-0.025534,-0.186592,0.002942,-0.139983,0.064148,0.489204,0.366935,0.325092,0.43199,0.406156,465.0,309.0,487.0,367.0,559.0,185.530470,190.954046,186.332667,183.441558,188.131868,9.530861,9.695044,9.332536,8.979801,9.438252,0.588935,0.600621,0.642928,0.671501,0.618356,0.027302,0.028893,0.026742,0.024196,0.027880
2,-0.053306,-0.179221,-0.027866,-0.126996,0.038964,0.473628,0.373694,0.307866,0.41874,0.386402,456.0,286.0,466.0,376.0,543.0,186.378621,191.836164,187.302697,183.040959,189.066933,9.444549,9.636759,10.041677,9.510485,9.351177,0.594889,0.605392,0.646678,0.675541,0.622136,0.028107,0.028659,0.027761,0.024343,0.027275

In [6]:
test.sort_values(by="MSFT.O mean ret", ascending=False).head(display)

,AAPL.O mean ret,MSFT.O mean ret,INTC.O mean ret,AMZN.O mean ret,GS.N mean ret,AAPL.O ret,MSFT.O ret,INTC.O ret,AMZN.O ret,GS.N ret,AAPL.O improvs,MSFT.O improvs,INTC.O improvs,AMZN.O improvs,GS.N improvs,AAPL.O falses,MSFT.O falses,INTC.O falses,AMZN.O falses,GS.N falses,AAPL.O falses.1,MSFT.O falses.1,INTC.O falses.1,AMZN.O falses.1,GS.N falses.1,AAPL.O f1 mean,MSFT.O f1 mean,INTC.O f1 mean,AMZN.O f1 mean,GS.N f1 mean,AAPL.O f1 std,MSFT.O f1 std,INTC.O f1 std,AMZN.O f1 std,GS.N f1 std
0,0.077936,-0.155093,0.042136,-0.104213,0.171643,0.561194,0.382017,0.352298,0.461920,0.443409,565.0,320.0,553.0,423.0,650.0,182.755245,188.840160,185.297702,182.582418,185.976024,10.144606,10.071168,9.439136,9.509230,9.613710,0.586011,0.597371,0.635753,0.668893,0.615714,0.029480,0.029270,0.026630,0.024903,0.028137
4,-0.135420,-0.173718,-0.042158,-0.133247,0.035495,0.465519,0.342318,0.279153,0.386308,0.349359,361.0,282.0,445.0,365.0,553.0,188.084915,192.146853,188.027972,183.719281,189.165834,9.263357,9.356891,9.250579,9.312471,9.256267,0.597060,0.609055,0.651066,0.676677,0.626171,0.027087,0.028299,0.026045,0.023527,0.026626
7,-0.104694,-0.174513,-0.049504,-0.118001,-0.006195,0.445974,0.351914,0.287474,0.380567,0.369990,394.0,298.0,437.0,355.0,484.0,188.589411,193.241758,188.538462,183.363636,189.566434,9.769660,9.557693,9.774291,9.298905,9.109656,0.602683,0.611865,0.655187,0.680191,0.630241,0.026950,0.026796,0.026751,0.023120,0.025574

In [7]:
test.sort_values(by="MSFT.O improvs", ascending=False).head(display)

,AAPL.O mean ret,MSFT.O mean ret,INTC.O mean ret,AMZN.O mean ret,GS.N mean ret,AAPL.O ret,MSFT.O ret,INTC.O ret,AMZN.O ret,GS.N ret,AAPL.O improvs,MSFT.O improvs,INTC.O improvs,AMZN.O improvs,GS.N improvs,AAPL.O falses,MSFT.O falses,INTC.O falses,AMZN.O falses,GS.N falses,AAPL.O falses.1,MSFT.O falses.1,INTC.O falses.1,AMZN.O falses.1,GS.N falses.1,AAPL.O f1 mean,MSFT.O f1 mean,INTC.O f1 mean,AMZN.O f1 mean,GS.N f1 mean,AAPL.O f1 std,MSFT.O f1 std,INTC.O f1 std,AMZN.O f1 std,GS.N f1 std
0,0.077936,-0.155093,0.042136,-0.104213,0.171643,0.561194,0.382017,0.352298,0.461920,0.443409,565.0,320.0,553.0,423.0,650.0,182.755245,188.840160,185.297702,182.582418,185.976024,10.144606,10.071168,9.439136,9.509230,9.613710,0.586011,0.597371,0.635753,0.668893,0.615714,0.029480,0.029270,0.026630,0.024903,0.028137
1,-0.025534,-0.186592,0.002942,-0.139983,0.064148,0.489204,0.366935,0.325092,0.431990,0.406156,465.0,309.0,487.0,367.0,559.0,185.530470,190.954046,186.332667,183.441558,188.131868,9.530861,9.695044,9.332536,8.979801,9.438252,0.588935,0.600621,0.642928,0.671501,0.618356,0.027302,0.028893,0.026742,0.024196,0.027880
3,-0.077429,-0.180148,-0.055663,-0.130571,0.028624,0.462829,0.361479,0.303759,0.404385,0.374372,413.0,302.0,411.0,365.0,522.0,187.662338,192.126873,187.778222,183.417582,189.094905,9.340336,9.922040,9.726190,9.128716,9.155762,0.596030,0.608203,0.651560,0.677443,0.625747,0.027487,0.028643,0.027002,0.023820,0.027392

In [8]:
test.sort_values(by="INTC.O mean ret", ascending=False).head(display)

,AAPL.O mean ret,MSFT.O mean ret,INTC.O mean ret,AMZN.O mean ret,GS.N mean ret,AAPL.O ret,MSFT.O ret,INTC.O ret,AMZN.O ret,GS.N ret,AAPL.O improvs,MSFT.O improvs,INTC.O improvs,AMZN.O improvs,GS.N improvs,AAPL.O falses,MSFT.O falses,INTC.O falses,AMZN.O falses,GS.N falses,AAPL.O falses.1,MSFT.O falses.1,INTC.O falses.1,AMZN.O falses.1,GS.N falses.1,AAPL.O f1 mean,MSFT.O f1 mean,INTC.O f1 mean,AMZN.O f1 mean,GS.N f1 mean,AAPL.O f1 std,MSFT.O f1 std,INTC.O f1 std,AMZN.O f1 std,GS.N f1 std
0,0.077936,-0.155093,0.042136,-0.104213,0.171643,0.561194,0.382017,0.352298,0.46192,0.443409,565.0,320.0,553.0,423.0,650.0,182.755245,188.840160,185.297702,182.582418,185.976024,10.144606,10.071168,9.439136,9.509230,9.613710,0.586011,0.597371,0.635753,0.668893,0.615714,0.029480,0.029270,0.026630,0.024903,0.028137
1,-0.025534,-0.186592,0.002942,-0.139983,0.064148,0.489204,0.366935,0.325092,0.43199,0.406156,465.0,309.0,487.0,367.0,559.0,185.530470,190.954046,186.332667,183.441558,188.131868,9.530861,9.695044,9.332536,8.979801,9.438252,0.588935,0.600621,0.642928,0.671501,0.618356,0.027302,0.028893,0.026742,0.024196,0.027880
2,-0.053306,-0.179221,-0.027866,-0.126996,0.038964,0.473628,0.373694,0.307866,0.41874,0.386402,456.0,286.0,466.0,376.0,543.0,186.378621,191.836164,187.302697,183.040959,189.066933,9.444549,9.636759,10.041677,9.510485,9.351177,0.594889,0.605392,0.646678,0.675541,0.622136,0.028107,0.028659,0.027761,0.024343,0.027275

In [9]:
test.sort_values(by="INTC.O improvs", ascending=False).head(display)

,AAPL.O mean ret,MSFT.O mean ret,INTC.O mean ret,AMZN.O mean ret,GS.N mean ret,AAPL.O ret,MSFT.O ret,INTC.O ret,AMZN.O ret,GS.N ret,AAPL.O improvs,MSFT.O improvs,INTC.O improvs,AMZN.O improvs,GS.N improvs,AAPL.O falses,MSFT.O falses,INTC.O falses,AMZN.O falses,GS.N falses,AAPL.O falses.1,MSFT.O falses.1,INTC.O falses.1,AMZN.O falses.1,GS.N falses.1,AAPL.O f1 mean,MSFT.O f1 mean,INTC.O f1 mean,AMZN.O f1 mean,GS.N f1 mean,AAPL.O f1 std,MSFT.O f1 std,INTC.O f1 std,AMZN.O f1 std,GS.N f1 std
0,0.077936,-0.155093,0.042136,-0.104213,0.171643,0.561194,0.382017,0.352298,0.46192,0.443409,565.0,320.0,553.0,423.0,650.0,182.755245,188.840160,185.297702,182.582418,185.976024,10.144606,10.071168,9.439136,9.509230,9.613710,0.586011,0.597371,0.635753,0.668893,0.615714,0.029480,0.029270,0.026630,0.024903,0.028137
1,-0.025534,-0.186592,0.002942,-0.139983,0.064148,0.489204,0.366935,0.325092,0.43199,0.406156,465.0,309.0,487.0,367.0,559.0,185.530470,190.954046,186.332667,183.441558,188.131868,9.530861,9.695044,9.332536,8.979801,9.438252,0.588935,0.600621,0.642928,0.671501,0.618356,0.027302,0.028893,0.026742,0.024196,0.027880
2,-0.053306,-0.179221,-0.027866,-0.126996,0.038964,0.473628,0.373694,0.307866,0.41874,0.386402,456.0,286.0,466.0,376.0,543.0,186.378621,191.836164,187.302697,183.040959,189.066933,9.444549,9.636759,10.041677,9.510485,9.351177,0.594889,0.605392,0.646678,0.675541,0.622136,0.028107,0.028659,0.027761,0.024343,0.027275

In [10]:
test.sort_values(by="AMZN.O mean ret", ascending=False).head(display)

,AAPL.O mean ret,MSFT.O mean ret,INTC.O mean ret,AMZN.O mean ret,GS.N mean ret,AAPL.O ret,MSFT.O ret,INTC.O ret,AMZN.O ret,GS.N ret,AAPL.O improvs,MSFT.O improvs,INTC.O improvs,AMZN.O improvs,GS.N improvs,AAPL.O falses,MSFT.O falses,INTC.O falses,AMZN.O falses,GS.N falses,AAPL.O falses.1,MSFT.O falses.1,INTC.O falses.1,AMZN.O falses.1,GS.N falses.1,AAPL.O f1 mean,MSFT.O f1 mean,INTC.O f1 mean,AMZN.O f1 mean,GS.N f1 mean,AAPL.O f1 std,MSFT.O f1 std,INTC.O f1 std,AMZN.O f1 std,GS.N f1 std
0,0.077936,-0.155093,0.042136,-0.104213,0.171643,0.561194,0.382017,0.352298,0.461920,0.443409,565.0,320.0,553.0,423.0,650.0,182.755245,188.840160,185.297702,182.582418,185.976024,10.144606,10.071168,9.439136,9.509230,9.613710,0.586011,0.597371,0.635753,0.668893,0.615714,0.029480,0.029270,0.026630,0.024903,0.028137
10,-0.139768,-0.185956,-0.062506,-0.116014,-0.033038,0.413093,0.361519,0.277157,0.367887,0.341859,354.0,292.0,419.0,384.0,453.0,189.583417,193.847153,188.386613,183.270729,190.123876,8.991401,9.322747,9.517950,9.154651,9.434439,0.604076,0.612951,0.657610,0.681650,0.631785,0.025739,0.026801,0.025315,0.022330,0.025940
7,-0.104694,-0.174513,-0.049504,-0.118001,-0.006195,0.445974,0.351914,0.287474,0.380567,0.369990,394.0,298.0,437.0,355.0,484.0,188.589411,193.241758,188.538462,183.363636,189.566434,9.769660,9.557693,9.774291,9.298905,9.109656,0.602683,0.611865,0.655187,0.680191,0.630241,0.026950,0.026796,0.026751,0.023120,0.025574

In [11]:
test.sort_values(by="AMZN.O improvs", ascending=False).head(display)

,AAPL.O mean ret,MSFT.O mean ret,INTC.O mean ret,AMZN.O mean ret,GS.N mean ret,AAPL.O ret,MSFT.O ret,INTC.O ret,AMZN.O ret,GS.N ret,AAPL.O improvs,MSFT.O improvs,INTC.O improvs,AMZN.O improvs,GS.N improvs,AAPL.O falses,MSFT.O falses,INTC.O falses,AMZN.O falses,GS.N falses,AAPL.O falses.1,MSFT.O falses.1,INTC.O falses.1,AMZN.O falses.1,GS.N falses.1,AAPL.O f1 mean,MSFT.O f1 mean,INTC.O f1 mean,AMZN.O f1 mean,GS.N f1 mean,AAPL.O f1 std,MSFT.O f1 std,INTC.O f1 std,AMZN.O f1 std,GS.N f1 std
0,0.077936,-0.155093,0.042136,-0.104213,0.171643,0.561194,0.382017,0.352298,0.461920,0.443409,565.0,320.0,553.0,423.0,650.0,182.755245,188.840160,185.297702,182.582418,185.976024,10.144606,10.071168,9.439136,9.509230,9.613710,0.586011,0.597371,0.635753,0.668893,0.615714,0.029480,0.029270,0.026630,0.024903,0.028137
6,-0.127499,-0.190984,-0.067389,-0.118508,-0.008848,0.444941,0.357122,0.281873,0.406640,0.357420,389.0,286.0,403.0,392.0,490.0,188.447552,193.209790,188.805195,183.238761,189.813187,9.698531,9.675430,9.412811,9.172782,9.341952,0.599701,0.610690,0.652487,0.679472,0.628285,0.027691,0.027622,0.026208,0.023237,0.026294
10,-0.139768,-0.185956,-0.062506,-0.116014,-0.033038,0.413093,0.361519,0.277157,0.367887,0.341859,354.0,292.0,419.0,384.0,453.0,189.583417,193.847153,188.386613,183.270729,190.123876,8.991401,9.322747,9.517950,9.154651,9.434439,0.604076,0.612951,0.657610,0.681650,0.631785,0.025739,0.026801,0.025315,0.022330,0.025940

In [12]:
test.sort_values(by="GS.N mean ret", ascending=False).head(display)

,AAPL.O mean ret,MSFT.O mean ret,INTC.O mean ret,AMZN.O mean ret,GS.N mean ret,AAPL.O ret,MSFT.O ret,INTC.O ret,AMZN.O ret,GS.N ret,AAPL.O improvs,MSFT.O improvs,INTC.O improvs,AMZN.O improvs,GS.N improvs,AAPL.O falses,MSFT.O falses,INTC.O falses,AMZN.O falses,GS.N falses,AAPL.O falses.1,MSFT.O falses.1,INTC.O falses.1,AMZN.O falses.1,GS.N falses.1,AAPL.O f1 mean,MSFT.O f1 mean,INTC.O f1 mean,AMZN.O f1 mean,GS.N f1 mean,AAPL.O f1 std,MSFT.O f1 std,INTC.O f1 std,AMZN.O f1 std,GS.N f1 std
0,0.077936,-0.155093,0.042136,-0.104213,0.171643,0.561194,0.382017,0.352298,0.46192,0.443409,565.0,320.0,553.0,423.0,650.0,182.755245,188.840160,185.297702,182.582418,185.976024,10.144606,10.071168,9.439136,9.509230,9.613710,0.586011,0.597371,0.635753,0.668893,0.615714,0.029480,0.029270,0.026630,0.024903,0.028137
1,-0.025534,-0.186592,0.002942,-0.139983,0.064148,0.489204,0.366935,0.325092,0.43199,0.406156,465.0,309.0,487.0,367.0,559.0,185.530470,190.954046,186.332667,183.441558,188.131868,9.530861,9.695044,9.332536,8.979801,9.438252,0.588935,0.600621,0.642928,0.671501,0.618356,0.027302,0.028893,0.026742,0.024196,0.027880
2,-0.053306,-0.179221,-0.027866,-0.126996,0.038964,0.473628,0.373694,0.307866,0.41874,0.386402,456.0,286.0,466.0,376.0,543.0,186.378621,191.836164,187.302697,183.040959,189.066933,9.444549,9.636759,10.041677,9.510485,9.351177,0.594889,0.605392,0.646678,0.675541,0.622136,0.028107,0.028659,0.027761,0.024343,0.027275

In [13]:
test.sort_values(by="GS.N improvs", ascending=False).head(display)

,AAPL.O mean ret,MSFT.O mean ret,INTC.O mean ret,AMZN.O mean ret,GS.N mean ret,AAPL.O ret,MSFT.O ret,INTC.O ret,AMZN.O ret,GS.N ret,AAPL.O improvs,MSFT.O improvs,INTC.O improvs,AMZN.O improvs,GS.N improvs,AAPL.O falses,MSFT.O falses,INTC.O falses,AMZN.O falses,GS.N falses,AAPL.O falses.1,MSFT.O falses.1,INTC.O falses.1,AMZN.O falses.1,GS.N falses.1,AAPL.O f1 mean,MSFT.O f1 mean,INTC.O f1 mean,AMZN.O f1 mean,GS.N f1 mean,AAPL.O f1 std,MSFT.O f1 std,INTC.O f1 std,AMZN.O f1 std,GS.N f1 std
0,0.077936,-0.155093,0.042136,-0.104213,0.171643,0.561194,0.382017,0.352298,0.461920,0.443409,565.0,320.0,553.0,423.0,650.0,182.755245,188.840160,185.297702,182.582418,185.976024,10.144606,10.071168,9.439136,9.509230,9.613710,0.586011,0.597371,0.635753,0.668893,0.615714,0.029480,0.029270,0.026630,0.024903,0.028137
1,-0.025534,-0.186592,0.002942,-0.139983,0.064148,0.489204,0.366935,0.325092,0.431990,0.406156,465.0,309.0,487.0,367.0,559.0,185.530470,190.954046,186.332667,183.441558,188.131868,9.530861,9.695044,9.332536,8.979801,9.438252,0.588935,0.600621,0.642928,0.671501,0.618356,0.027302,0.028893,0.026742,0.024196,0.027880
4,-0.135420,-0.173718,-0.042158,-0.133247,0.035495,0.465519,0.342318,0.279153,0.386308,0.349359,361.0,282.0,445.0,365.0,553.0,188.084915,192.146853,188.027972,183.719281,189.165834,9.263357,9.356891,9.250579,9.312471,9.256267,0.597060,0.609055,0.651066,0.676677,0.626171,0.027087,0.028299,0.026045,0.023527,0.026626

In [19]:
heads = 1
lst = list(test.sort_values(by=f"AAPL.O improvs", ascending=False).head(heads).index)

for stock in stocks:
    # lst2 = list(test.sort_values(by=f"{stock} mean ret", ascending=False).head(heads).index)
    lst1 = list(test.sort_values(by=f"{stock} improvs", ascending=False).head(heads).index)
    lst = list(set(lst) & set(lst1))
    # lst = list(set(lst) & set(lst2))

lst

[0]